# Generated by Django 5.1.5 on 2025-02-23 14:03

import ckeditor.fields
import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_personalinfo_bio_alter_project_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Contact Information', 'verbose_name_plural': 'Contact Information'},
        ),
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'verbose_name': 'Personal Information', 'verbose_name_plural': 'Personal Information'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-is_featured', 'title'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='additional_contacts',
            field=models.JSONField(blank=True, default=dict, validators=[portfolio.models.validate_json_data], verbose_name='Additional Contacts'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='cv_link',
            field=models.URLField(verbose_name='CV Link'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='social_media_links',
            field=models.JSONField(default=dict, validators=[portfolio.models.validate_json_data], verbose_name='Social Media Links'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='additional_info',
            field=models.JSONField(blank=True, default=dict, validators=[portfolio.models.validate_json_data], verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='role',
            field=models.CharField(max_length=100, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload project images here', null=True, upload_to='projects/', verbose_name='Project Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(verbose_name='Project Link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.JSONField(blank=True, default=list, validators=[portfolio.models.validate_json_data], verbose_name='Technologies Used'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Project Title'),
        ),
    ]
