# Generated by Django 5.1.5 on 2025-02-23 18:53

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_contactinfo_options_alter_personalinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='bio',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Project Description'),
        ),
    ]
