# Generated by Django 5.1.5 on 2025-02-23 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_project_technologies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='bio',
        ),
    ]
